ERC_Transformer:
  seq_len: 51
  subcarrier_num: 2025
  RxTx_num: 6
  embedding_type: 'gaussian_range' #'spatial_temporal'
  d_model_tem: 1536
  d_model_cha: 306
  n_heads_tem: 6
  n_heads_cha: 6
  dim_feedforward_tem: 2048
  dim_feedforward_cha: 768
  kernel_sizes:
    - 1
    - 3
    - 5
    - 7
  num_layers: 3
  dropout: 0.1
  activation: 'gelu'
  norm_first: True
  return_channel_stream: True
  gaussian_k: 12
  use_mix_attn: True

AggregationBlock:
  in_length: 51
  in_channels: 1536
  out_length: 12
  out_channels: 1024
  activation: 'gelu'
  dropout: 0.1

FullModel:
  vae_latent_shape:
    - 1024
    - 3
    - 4
  activation: 'gelu'
  dropout: 0.1
  aggregation: 'cross'

Adapter_Block:
  in_length: 51
  in_channels: 3072
  out_length: 12
  out_channels: 1024
  activation: 'gelu'
  dropout: 0.1

Out_Adapter_Block:
  in_length: 51
  in_channels: 3072
  out_length: 48
  out_channels: 256
  activation: 'gelu'
  dropout: 0.1